### ISSUE TITLE
yoda-webhook does not handle well if owner (organisation) listed in `> issuesearch`does not exist

### ISSUE THREAD

**Issue by jens-markussen** [plan4hub/yoda#34]
Causes exception and yoda-webhook terminates.

```
yoda-webhook_1  | [2023-06-22T18:15:09.847] [WARN] default - Could not find app installation for owner: nosuchorg
yoda-webhook_1  | [2023-06-22T18:15:09.852] [ERROR] default - TypeError: Cannot read properties of null (reading 'paginate')
yoda-webhook_1  |     at /usr/app/issue-references.js:138:40
yoda-webhook_1  |     at new Promise (<anonymous>)
yoda-webhook_1  |     at getChildren (/usr/app/issue-references.js:131:9)
yoda-webhook_1  |     at /usr/app/issue-references.js:678:4
yoda-webhook_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jens-markussen** [comment]
Confirmed working
